version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: pipelines/EmpiricalMaps/EmpiricalMaps.wdl
    name: EmpiricalMaps
    authors:
      - orcid: 0000-0002-2021-6883
  - subclass: WDL
    primaryDescriptorPath: pipelines/EmpiricalSNPCalling/EmpiricalSNPCalling.wdl
    name: EmpiricalSNPCalling
    authors:
      - orcid: 0000-0002-2021-6883
  - subclass: WDL
    primaryDescriptorPath: pipelines/PreprocessingReads/PreprocessingReads.wdl
    name: PreprocessingReads
    authors:
      - orcid: 0000-0002-2021-6883
  - subclass: WDL
    primaryDescriptorPath: pipelines/SimulatedReads2Map/SimulatedReads2Map.wdl
    name: SimulatedReads2Map
    authors:
      - orcid: 0000-0002-2021-6883
  - subclass: WDL
    primaryDescriptorPath: EmpiricalReads2Map/EmpiricalReads2Map/EmpiricalReads2Map.wdl
    name: EmpiricalReads2Map
    authors:
      - orcid: 0000-0002-2021-6883