version: 2.1


machine_default: &machine_default
  machine:
    image: ubuntu-2004:202010-01


jobs:
  wdl-validate:
    docker:
      - image: broadinstitute/womtool:85-4a6ad8e
    steps:
      - checkout
      - run:
          name: Checking WDL sintax
          command: for i in *.wdl; do echo $i; java -jar /app/womtool.jar validate $i; done

  run-tasks-tests:
    <<: *machine_default
    environment:
      MINIWDL__FILE_IO__ALLOW_ANY_INPUT: "true"  # required (probably) because of some "Strigs" used as "File" in WDL
    steps:
      - checkout

      - run: pip3 install -r tests/requirements.txt
      - run: pytest --tag create_alignment_from_families_files tests/


  release-develop:
    <<: *machine_default
    steps:
      - checkout
      - run: for i in pipelines/*/*.wdl; do echo $i; bash .scripts/release_pipeline_to_github.sh -e dev -p $i; done


workflows:
  test-and-release:
    jobs:
      - wdl-validate
      - run-tasks-tests:
          requires:
            - wdl-validate
      - release-develop:
          requires:
            - run-tasks-tests
