version: 2.1


machine_default: &machine_default
  machine:
    image: ubuntu-2004:202010-01


jobs:
  wdl-validate:
    docker:
      - image: broadinstitute/womtool:85-4a6ad8e
    steps:
      - checkout
      - run:
          name: Checking WDL sintax
          command: for i in pipelines/*/*.wdl; do echo $i; java -jar /app/womtool.jar validate $i; done

  run-tasks-tests:
    <<: *machine_default
    environment:
      MINIWDL__FILE_IO__ALLOW_ANY_INPUT: "true"  # required (probably) because of some "Strigs" used as "File" in WDL
    steps:
      - checkout

      - run: pip3 install -r tests/requirements.txt
      - run: pytest --git-aware --tag freebayes tests/
      - run: pytest --git-aware --tag gatk tests/

  release-to-github:
    <<: *machine_default
    parameters:
      env:
        description: The target environment of the deployment
        type: enum
        enum: ["dev", "prod"]
    steps:
      - checkout
      - run:
          name: "Prepare releases and publish to GitHub"
          command: for i in pipelines/*/*.wdl; do echo $i; bash .scripts/release_pipeline_to_github.sh -e << parameters.env >> -p $i; done


workflows:
  test-and-release:
    jobs:
      - wdl-validate
      - run-tasks-tests:
          requires:
            - wdl-validate
      - release-to-github:
          name: release-development-version
          env: "dev"
          requires:
            - run-tasks-tests
          filters:
            branches:
              only:
                - develop
      - release-to-github:
          name: release-production-version
          env: "dev"
          filters:
            branches:
              only:
                - main
