version: 2.1

jobs:
  wdl-validate:
    docker:
      - image: broadinstitute/womtool:85
    steps:
      - checkout
      - run:
          name: Checking WDL sintax
          command: for i in *.wdl; do echo $i; java -jar /app/womtool.jar validate $i; done


workflows:
  test-and-release:
    jobs:
      - wdl-validate
