---
title: "F2 simulations results"
date: "`r Sys.Date()`"
author: "[Statistical Genetics Lab](http://statgen.esalq.usp.br) <br/> Department of Genetics <br/> Luiz de Queiroz College of Agriculture <br/> University of São Paulo"
output:
    rmdformats::readthedown:
      css: readthedownstatgen.css
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")

opts_knit$set(width=75)
```

This report include analysis with all output files generated by the simulations workflow for F2 populations.

Output files:

* 



# Packages

```{r}
library(ggplot2)
library(reshape2)
```

```{r}

# Graphics

maps.names <- c("map.df",
                "map.up",
                "map.poly",
                "map.super")

# Total size
genotype <- rep(maps.names, each=n.sim)

tot.size <- list()
for(i in 1:length(maps.names))
  tot.size[[i]] <- sapply(get(maps.names[i])[[3]], function(x) x[length(x)])
tot.size <- unlist(tot.size)

tot.size.df <- data.frame(genotype, tot.size)

p <- ggplot(tot.size.df, aes(x=genotype, y=tot.size)) + geom_boxplot() +
  labs(title= paste0("Total size ", depth[j]) ,x="genotype and probs", y = "cM")   + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1), 
        panel.background = element_rect(fill = "lightblue",
                                        colour = "lightblue",
                                        size = 0.5, linetype = "solid")) +
  geom_hline(yintercept = 12, color = "darkgreen") 



ggsave(p,filename = paste0("Tot.size.",depth[j],".jpg"))
p

# Distances between markers

df.dist.part <- data.frame()
for(i in 1:length(maps.names)){
  dist.part <- unlist(get(maps.names[i])[[2]])
  df.dist.part <- rbind(df.dist.part, data.frame(geno=rep(maps.names[i], length(dist.part)), dist = dist.part))
}


p <- ggplot(df.dist.part, aes(x=geno, y=dist)) + geom_boxplot() +
  labs(title= paste0("Distances ", depth[j]) ,x="genotype and probs", y = "cM")   + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1), 
        panel.background = element_rect(fill = "lightblue",
                                        colour = "lightblue",
                                        size = 0.5, linetype = "solid")) +
  geom_hline(yintercept = 1, color = "darkgreen") 

ggsave(p,filename = paste0("Dists.",depth[j],".jpg"))
p
```





