---
title: "Introduction - OneMap workflows"
date: "`r Sys.Date()`"
author: "[Statistical Genetics Lab](http://statgen.esalq.usp.br) <br/> Department of Genetics <br/> Luiz de Queiroz College of Agriculture <br/> University of São Paulo"
output:
    rmdformats::readthedown:
      css: readthedownstatgen.css
---

OneMap workflow uses [WDL](https://github.com/openwdl/wdl/blob/master/versions/1.0/SPEC.md) language and [cromwell](https://github.com/broadinstitute/cromwell) from [Broad Institute](https://github.com/broadinstitute) to offer a user friendly and optimized memory, CPU and time workflows to build linkage maps with OneMap. There are two main workflows called SimulatedReads and EmpiricalReads. The first performs population and RADseq fastq files simulations for a chromosome, SNP and genotype calling with five different software and genetic map building with OneMap and Gusmap. EmpiricalReads receives fastq files from empirical data and also performs the SNP and genotype calling and map building. 	 
 
 The main workflows are composed of sub-workflows that can also be useful for users, they are located at the `tasks` folder. The sub-workflows are composed of tasks that can be found at the end of each `.wdl` file and at `utils.wdl` and `utilsR.wdl`. 	 
 
 [Docker](https://hub.docker.com/) images were built to each one of the tasks, then users need only to download the most recent version of Cromwell, install its requirements and docker. If running without sudo permission users can use [singularity](https://singularity.lbl.gov/docs-docker) instead of directly docker. See `.configurations` directory and it's [instructions]() to use singularity. 	 
  
 The WDL and Cromwell system is also made to be easily expansible. Users can change arguments or implement other software into the analysis. 	 
  
 The main goals of OneMap workflows are test software capabilities in ideal scenarios (SimulatedReads) and empirical data (EmpiricalReads). SimulatedReads also gives a safe method to test new functionalities implemented in OneMap and EmpiricalReads gives a fast and automatic method to select the best software to build linkage maps and answer biological questions for any empirical data.

Output datasets from each main workflow can be easily evaluated in a shiny app called [onemap_workflows_app](). You need to submit your output to the app, and the final page gives the possibility to download the OneMap or Gusmap object containing the combination of software and parameters you selected. By now, only one chromosome is evaluated in both workflows, but, downloading the OneMap or Gusmap object you can repeat the map building process in R for other chromosomes without spent all the time needed to compare all the methods. We show an example of these usages in `Quickstart` below.



